"""Workbook parsing.

Every workbook here is generated by `tests/fixtures/workbooks.py`. The tool is never run against a
real NFR spreadsheet while building (CLAUDE.md), and these fixtures are built to mirror the shipped
template's structure while making wrong answers visible: the `Example` column always differs from
the `Value` column, so a parser reading the wrong one fails rather than passing by coincidence.
"""

from __future__ import annotations

import pytest

from perfgen.ir.models import (
    AuthStrategy,
    AuthType,
    Method,
    ProfileId,
    Severity,
    SlaMetric,
    SlaUnit,
    ThroughputUnit,
)
from perfgen.parse import parse_workbook
from tests.fixtures.workbooks import (
    DEFAULT_APPLICATION,
    WorkbookSpec,
    blank_spec,
    drop_application_row,
    profile_row,
    set_application_value,
    write_workbook,
)


def parse(tmp_path, spec: WorkbookSpec | None = None):
    return parse_workbook(write_workbook(tmp_path / "spec.xlsx", spec))


def gap_for(result, field_path: str):
    return next((g for g in result.gaps if g.field == field_path), None)


# --------------------------------------------------------------------------------------------
# The happy path
# --------------------------------------------------------------------------------------------


def test_valid_workbook_parses_without_blocking_gaps(tmp_path):
    result = parse(tmp_path)
    assert result.blocking == []
    assert result.ok


def test_valid_workbook_still_reports_its_structural_warnings(tmp_path):
    """Parsing folds in the structural checks, so nothing is saved up for emit time."""
    fields = {g.field for g in parse(tmp_path).gaps}
    assert fields == {"auth.refresh_required", "auth.token_extract.expr"}


def test_application_fields(tmp_path):
    ir = parse(tmp_path).ir
    assert ir.application.name == "Claims intake service"
    assert ir.application.base_url == "https://perf-claims.example.internal"
    assert ir.application.base_path == "/v1"


def test_value_column_is_read_not_the_example_column(tmp_path):
    """The Example column is guidance. Reading it yields a plausible but wrong spec."""
    ir = parse(tmp_path).ir
    assert ir.application.name != "Service request portal"
    assert ir.application.base_path != "/api/v2"
    assert ir.auth.token_request.credential_refs == ["claims-perf-id", "claims-perf-secret"]


def test_empty_value_with_a_populated_example_parses_as_absent(tmp_path):
    """API reference location is blank in Value and filled in Example."""
    ir = parse(tmp_path).ir
    assert ir.application.api_reference is None


def test_auth_enums_are_normalised(tmp_path):
    ir = parse(tmp_path).ir
    assert ir.auth.type is AuthType.OAUTH2_CLIENT_CREDENTIALS
    assert ir.auth.strategy is AuthStrategy.SHARED_SETUP
    assert ir.auth.lifetime_seconds == 3600
    assert ir.auth.header_name == "Authorization"


def test_newline_separated_cells_become_lists(tmp_path):
    ir = parse(tmp_path).ir
    assert ir.auth.token_request.param_names == ["grant_type", "client_id", "client_secret"]


def test_token_expression_is_left_unknown_for_the_probe(tmp_path):
    """M2 never guesses where the token lives in the response; the probe finds it."""
    ir = parse(tmp_path).ir
    assert ir.auth.token_extract.expr is None
    assert ir.auth.token_extract.var == "authToken"


def test_flows_and_unit_conversions(tmp_path):
    ir = parse(tmp_path).ir
    assert [f.id for f in ir.flows] == ["F01", "F02"]
    assert ir.flows[0].share_pct == 60
    assert ir.flows[0].think_time_ms == 3000  # 3 s -> ms
    assert ir.flows[0].probe_safe is True
    assert ir.flows[1].probe_safe is False


def test_steps_are_ordered_and_attached_to_their_flow(tmp_path):
    ir = parse(tmp_path).ir
    assert [s.index for s in ir.flows[0].steps] == [1, 2]
    assert ir.flows[0].steps[1].path == "/catalogue/items/{itemId}"
    assert ir.flows[0].steps[0].method is Method.GET


def test_content_type_is_inferred_from_a_json_body(tmp_path):
    ir = parse(tmp_path).ir
    create = ir.flows[1].steps[0]
    assert create.body == '{"type":"standard"}'
    assert create.content_type == "application/json"


def test_load_profiles_and_duration_conversion(tmp_path):
    ir = parse(tmp_path).ir
    by_id = {p.id: p for p in ir.load_profiles}
    assert by_id[ProfileId.BASELINE].enabled is True
    assert by_id[ProfileId.BASELINE].users == 25
    assert by_id[ProfileId.BASELINE].duration_s == 1800  # 30 min -> s
    assert by_id[ProfileId.CAPACITY].enabled is False
    assert by_id[ProfileId.ENDURANCE].duration_s == 14400  # 240 min


def test_throughput_units_are_normalised(tmp_path):
    ir = parse(tmp_path).ir
    baseline = next(p for p in ir.load_profiles if p.id is ProfileId.BASELINE)
    assert baseline.throughput.value == 1200
    assert baseline.throughput.unit is ThroughputUnit.TPH


def test_sla_rows_are_normalised(tmp_path):
    ir = parse(tmp_path).ir
    assert ir.sla[0].scope == "all"  # "All flows"
    assert ir.sla[0].metric is SlaMetric.RESPONSE_TIME_P95
    assert ir.sla[1].scope == "F01"
    assert ir.sla[2].unit is SlaUnit.PERCENT  # "%"


def test_refresh_required_is_derived_from_the_parsed_durations(tmp_path):
    """Endurance runs 240 min against a 3600 s token lifetime."""
    ir = parse(tmp_path).ir
    assert ir.auth.refresh_required is True


def test_provenance_records_the_source_workbook(tmp_path):
    ir = parse(tmp_path).ir
    assert ir.provenance.source_workbook == "spec.xlsx"
    assert ir.provenance.probe.performed is False


def test_no_correlations_are_invented(tmp_path):
    """Correlations come from the probe and the correlation engine, not the spreadsheet."""
    ir = parse(tmp_path).ir
    assert all(not step.extracts for flow in ir.flows for step in flow.steps)


# --------------------------------------------------------------------------------------------
# The mangled spec: users insert rows, rename sections and reorder columns
# --------------------------------------------------------------------------------------------


def test_inserted_rows_above_the_header_do_not_break_parsing(tmp_path):
    spec = WorkbookSpec(blank_rows_before_header=3)
    result = parse(tmp_path, spec)
    assert result.ok, [g.message for g in result.blocking]
    assert result.ir.application.name == "Claims intake service"


def test_blank_rows_between_data_rows_are_skipped(tmp_path):
    spec = WorkbookSpec(extra_blank_rows_in_body=2)
    result = parse(tmp_path, spec)
    assert result.ok, [g.message for g in result.blocking]
    assert len(result.ir.flows) == 2
    assert len(result.ir.flows[0].steps) == 2


def test_renamed_section_dividers_do_not_break_parsing(tmp_path):
    """Section headings are decoration; fields are found by their own labels."""
    spec = WorkbookSpec(section_titles=("The application", "How we log in"))
    result = parse(tmp_path, spec)
    assert result.ok, [g.message for g in result.blocking]
    assert result.ir.auth.type is AuthType.OAUTH2_CLIENT_CREDENTIALS


def test_reordered_columns_are_located_by_header(tmp_path):
    spec = WorkbookSpec(
        column_order={
            "application": ["Example", "Notes", "Value", "Required", "Attribute"],
            "flows": [
                "Safe to run against this environment",
                "Share of load %",
                "Flow name",
                "Flow ID",
                "Think time between calls (s)",
            ],
            "profiles": [
                "Throughput unit",
                "Target throughput",
                "Duration (min)",
                "Ramp-up (s)",
                "Concurrent users",
                "Required",
                "Test type",
            ],
        }
    )
    result = parse(tmp_path, spec)
    assert result.ok, [g.message for g in result.blocking]
    assert result.ir.application.name == "Claims intake service"
    assert result.ir.flows[0].share_pct == 60
    baseline = next(p for p in result.ir.load_profiles if p.id is ProfileId.BASELINE)
    assert baseline.users == 25


def test_renamed_sheets_are_found(tmp_path):
    spec = WorkbookSpec(
        sheet_names={
            "application": "APPLICATION",
            "flows": "flows",
            "steps": "Flow Steps",
            "profiles": "Load Profiles",
            "sla": "SLAs",
        }
    )
    result = parse(tmp_path, spec)
    assert result.ok, [g.message for g in result.blocking]


def test_steps_out_of_row_order_are_sorted_by_step_number(tmp_path):
    spec = WorkbookSpec()
    spec.steps = [spec.steps[1], spec.steps[0], spec.steps[3], spec.steps[2]]
    ir = parse(tmp_path, spec).ir
    assert [s.index for s in ir.flows[0].steps] == [1, 2]
    assert ir.flows[0].steps[0].name == "Search catalogue"


def test_everything_mangled_at_once(tmp_path):
    """The brief's deliberately mangled spec, all knobs turned together."""
    spec = WorkbookSpec(
        blank_rows_before_header=2,
        extra_blank_rows_in_body=1,
        section_titles=("App", "Auth bits"),
        sheet_names={
            "application": "Application ",
            "flows": "FLOWS",
            "steps": "Steps",
            "profiles": "Load profiles",
            "sla": "SLA",
        },
        column_order={"flows": ["Flow name", "Flow ID", "Share of load %",
                                "Safe to run against this environment",
                                "Think time between calls (s)"]},
    )
    result = parse(tmp_path, spec)
    assert result.ok, [g.message for g in result.blocking]
    assert result.ir.application.name == "Claims intake service"
    assert result.ir.flows[0].think_time_ms == 3000


# --------------------------------------------------------------------------------------------
# The blank template: one run must produce the whole list
# --------------------------------------------------------------------------------------------

# Everything a completely empty specification is missing. A new user's first run looks like this,
# and getting a partial list means fixing the sheet, re-running, and discovering the next problem
# - three rounds instead of one.
BLANK_TEMPLATE_BLOCKING_FIELDS = {
    "application.name",
    "application.base_url",
    "auth.type",
    "flows",
    "flows.steps",
    "load_profiles",
}


def test_blank_template_reports_every_blocking_field_in_one_run(tmp_path):
    result = parse(tmp_path, blank_spec())

    assert result.ir is None
    assert {g.field for g in result.blocking} == BLANK_TEMPLATE_BLOCKING_FIELDS, (
        "a blank template must report its whole blocking list in a single run"
    )


def test_blank_template_load_profiles_gap_is_not_masked_by_the_application_sheet(tmp_path):
    """The regression this test exists for: an unbuildable IR used to hide the later sheets."""
    gap = gap_for(parse(tmp_path, blank_spec()), "load_profiles")
    assert gap is not None and gap.severity is Severity.BLOCKING
    assert "marked Required" in gap.message


def test_blank_template_reports_both_flows_and_flow_steps_separately(tmp_path):
    result = parse(tmp_path, blank_spec())
    flows_gap = gap_for(result, "flows")
    steps_gap = gap_for(result, "flows.steps")
    assert flows_gap is not None and "'Flows' sheet has no rows" in flows_gap.message
    assert steps_gap is not None and "'Flow steps' sheet has no rows" in steps_gap.message


def test_blank_template_says_auth_fields_cannot_be_judged_yet(tmp_path):
    """With Auth type unknown, the dependent fields are neither required nor not - say so."""
    result = parse(tmp_path, blank_spec())
    assert any("depends on 'Auth type'" in note for note in result.notes)
    assert not any(g.field == "auth.token_request.url" for g in result.gaps), (
        "a token endpoint must not be demanded before the auth type is known"
    )


def test_blank_template_every_message_names_a_sheet(tmp_path):
    """A field path alone does not tell a user which cell to go and fill in."""
    sheets = ("Application", "Flows", "Flow steps", "Load profiles", "SLA")
    for gap in parse(tmp_path, blank_spec()).blocking:
        assert any(name in gap.message for name in sheets), gap


def test_fixing_the_application_sheet_does_not_reveal_new_blockers(tmp_path):
    """The point of one-pass reporting: the second run has strictly fewer problems, not different
    ones."""
    first = {g.field for g in parse(tmp_path, blank_spec()).blocking}

    spec = blank_spec()
    set_application_value(spec, "Application name", "Fixed")
    set_application_value(spec, "Base URL", "https://fixed.example.internal")
    set_application_value(spec, "Auth type", "None")
    set_application_value(spec, "Account model", "Single shared")
    second = {g.field for g in parse(tmp_path, spec).blocking}

    assert second < first, f"new blockers appeared on the second run: {second - first}"


# --------------------------------------------------------------------------------------------
# Missing and invalid input: collected, never invented
# --------------------------------------------------------------------------------------------


def test_missing_application_name_is_blocking(tmp_path):
    spec = set_application_value(WorkbookSpec(), "Application name", None)
    result = parse(tmp_path, spec)
    gap = gap_for(result, "application.name")
    assert gap is not None and gap.severity is Severity.BLOCKING
    assert "Application, row" in gap.message
    assert result.ir is None


def test_deleted_label_row_is_reported_as_missing_not_empty(tmp_path):
    spec = drop_application_row(WorkbookSpec(), "Base URL")
    gap = gap_for(parse(tmp_path, spec), "application.base_url")
    assert gap is not None
    assert "missing from the sheet" in gap.message


def test_base_url_without_a_scheme_is_blocking(tmp_path):
    spec = set_application_value(WorkbookSpec(), "Base URL", "perf-claims.example.internal")
    gap = gap_for(parse(tmp_path, spec), "application.base_url")
    assert gap is not None and gap.severity is Severity.BLOCKING
    assert "no http:// or https:// scheme" in gap.message


def test_unrecognised_auth_type_is_blocking_and_lists_the_valid_values(tmp_path):
    spec = set_application_value(WorkbookSpec(), "Auth type", "OAuth3 magic")
    gap = gap_for(parse(tmp_path, spec), "auth.type")
    assert gap is not None and gap.severity is Severity.BLOCKING
    assert "oauth2 client credentials" in gap.message


def test_several_problems_are_all_reported_in_one_pass(tmp_path):
    """A user with three blank cells is told about three, not made to run the tool three times."""
    spec = WorkbookSpec()
    set_application_value(spec, "Application name", None)
    set_application_value(spec, "Base URL", None)
    set_application_value(spec, "Auth type", None)
    result = parse(tmp_path, spec)
    reported = {g.field for g in result.gaps}
    assert {"application.name", "application.base_url", "auth.type"} <= reported


def test_missing_sheet_is_blocking(tmp_path):
    spec = WorkbookSpec()
    spec.sheet_names["flows"] = "Something else"
    gap = gap_for(parse(tmp_path, spec), "sheet.Flows")
    assert gap is not None and gap.severity is Severity.BLOCKING


def test_flow_with_no_steps_is_blocking(tmp_path):
    spec = WorkbookSpec()
    spec.steps = [row for row in spec.steps if row[0] != "F02"]
    gap = gap_for(parse(tmp_path, spec), "flows.F02.steps")
    assert gap is not None and gap.severity is Severity.BLOCKING


def test_steps_for_an_unknown_flow_warn_and_are_ignored(tmp_path):
    spec = WorkbookSpec()
    spec.steps.append(["F99", 1, "Orphan", "GET", "/orphan", None, 200])
    result = parse(tmp_path, spec)
    gap = gap_for(result, "flows.F99")
    assert gap is not None and gap.severity is Severity.WARNING
    assert [f.id for f in result.ir.flows] == ["F01", "F02"]


def test_duplicate_step_numbers_within_a_flow_are_blocking(tmp_path):
    spec = WorkbookSpec()
    spec.steps[1][1] = 1  # F01 now has two step 1s
    gap = gap_for(parse(tmp_path, spec), "flows.F01.steps.index")
    assert gap is not None and gap.severity is Severity.BLOCKING


def test_invalid_method_is_blocking(tmp_path):
    spec = WorkbookSpec()
    spec.steps[0][3] = "FETCH"
    gap = gap_for(parse(tmp_path, spec), "flows.F01.steps.method")
    assert gap is not None and gap.severity is Severity.BLOCKING


def test_missing_expected_status_defaults_to_200_with_a_warning(tmp_path):
    spec = WorkbookSpec()
    spec.steps[0][6] = None
    result = parse(tmp_path, spec)
    gap = gap_for(result, "flows.F01.steps.expected_status")
    assert gap is not None and gap.severity is Severity.WARNING
    assert result.ir.flows[0].steps[0].expected_status == 200


def test_throughput_without_a_unit_is_blocking(tmp_path):
    """A rate with no unit is meaningless, and guessing one would change the test."""
    spec = WorkbookSpec()
    profile_row(spec, "Baseline")[6] = None
    gap = gap_for(parse(tmp_path, spec), "load_profiles.baseline.throughput.unit")
    assert gap is not None and gap.severity is Severity.BLOCKING


def test_unknown_test_type_row_warns_and_is_ignored(tmp_path):
    spec = WorkbookSpec()
    spec.profiles.append(["Soak forever", "Yes", 10, 10, 10, None, None])
    result = parse(tmp_path, spec)
    assert any(g.field == "load_profiles" and g.severity is Severity.WARNING for g in result.gaps)
    assert len(result.ir.load_profiles) == 4


def test_empty_sla_sheet_is_a_note_not_a_gap(tmp_path):
    """SLAs are optional, so an empty sheet is legal - but silence leaves the user guessing."""
    spec = WorkbookSpec()
    spec.slas = []
    result = parse(tmp_path, spec)

    assert result.ok
    assert not any("sla" in g.field for g in result.gaps)
    assert any("'SLA' sheet has no targets" in note for note in result.notes)
    assert result.ir.sla == []


def test_populated_sla_sheet_produces_no_note(tmp_path):
    assert not any("SLA" in note for note in parse(tmp_path).notes)


def test_unreadable_sla_row_warns_and_is_skipped(tmp_path):
    spec = WorkbookSpec()
    spec.slas.append(["All flows", "Vibes", 10, "ms"])
    result = parse(tmp_path, spec)
    assert any(g.field == "sla.metric" for g in result.gaps)
    assert len(result.ir.sla) == 3


def test_footnote_rows_are_not_read_as_data(tmp_path):
    """Every sheet ends with a paragraph of guidance in column A."""
    result = parse(tmp_path, WorkbookSpec(include_footnotes=True))
    assert [f.id for f in result.ir.flows] == ["F01", "F02"]
    assert len(result.ir.sla) == 3


def test_application_sheet_without_a_value_column_is_blocking(tmp_path):
    spec = WorkbookSpec(omit_columns={"application": ["Value"]})
    gap = gap_for(parse(tmp_path, spec), "application")
    assert gap is not None and gap.severity is Severity.BLOCKING
    assert "Example" in gap.message


@pytest.mark.parametrize(
    ("label", "value", "expected"),
    [
        ("Account model", "One per user", AuthStrategy.PER_THREAD),
        ("Account model", "Single shared", AuthStrategy.SHARED_SETUP),
    ],
)
def test_account_model_maps_to_strategy(tmp_path, label, value, expected):
    spec = set_application_value(WorkbookSpec(), label, value)
    assert parse(tmp_path, spec).ir.auth.strategy is expected


def test_auth_type_none_needs_no_token_fields(tmp_path):
    spec = WorkbookSpec()
    set_application_value(spec, "Auth type", "None")
    set_application_value(spec, "Auth header name", None)
    set_application_value(spec, "Auth header value format", None)
    set_application_value(spec, "Token endpoint URL", None)
    result = parse(tmp_path, spec)
    assert result.ok, [g.message for g in result.blocking]
    assert result.ir.auth.type is AuthType.NONE
    assert result.ir.auth.token_request is None


def test_oauth_without_a_token_endpoint_is_blocking(tmp_path):
    spec = set_application_value(WorkbookSpec(), "Token endpoint URL", None)
    gap = gap_for(parse(tmp_path, spec), "auth.token_request.url")
    assert gap is not None and gap.severity is Severity.BLOCKING


def test_value_format_without_a_token_placeholder_warns(tmp_path):
    spec = set_application_value(WorkbookSpec(), "Auth header value format", "Bearer")
    gap = gap_for(parse(tmp_path, spec), "auth.value_format")
    assert gap is not None and gap.severity is Severity.WARNING


def test_no_secret_values_are_read_from_the_workbook(tmp_path):
    """Only reference names ever reach the IR."""
    ir = parse(tmp_path).ir
    assert ir.auth.token_request.credential_refs == ["claims-perf-id", "claims-perf-secret"]
    assert all("secret" not in name or name.endswith("-secret") for name in
               ir.auth.token_request.credential_refs)


def test_every_default_application_label_is_recognised(tmp_path):
    """Guards against a label drifting in the fixture without the parser noticing."""
    result = parse(tmp_path)
    assert result.ok
    labels = {label for label, _, _ in DEFAULT_APPLICATION}
    assert "Account model" in labels and "Base URL" in labels


def test_non_ascii_spec_content_survives_parsing(tmp_path):
    """Real specs carry accents and non-Latin names; they must not break the run."""
    spec = WorkbookSpec()
    set_application_value(spec, "Application name", "Café commandes 注文")
    spec.flows[0][1] = "Recherche de dossier"

    result = parse(tmp_path, spec)
    assert result.ok, [g.message for g in result.blocking]
    assert result.ir.application.name == "Café commandes 注文"
    assert result.ir.flows[0].name == "Recherche de dossier"


def test_non_ascii_gap_message_can_be_printed_on_a_legacy_console(tmp_path, capsys):
    """A cp1252 console would otherwise raise UnicodeEncodeError and lose the whole report."""
    from perfgen.__main__ import main

    spec = WorkbookSpec()
    set_application_value(spec, "Application name", "Café commandes")
    set_application_value(spec, "Base URL", None)
    workbook = write_workbook(tmp_path / "spec.xlsx", spec)

    assert main(["parse", str(workbook), "--out", str(tmp_path / "ir")]) == 1
    assert "BLOCKING" in capsys.readouterr().out
